name: ProBID-Net
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - keras=2.8.0
  - tensorflow-gpu=2.8.1
  - cudatoolkit=10.1
  - cudnn=7.6.4
  - pandas
  - biopython
  - h5py
  - scipy
  - numpy
  - protobuf
  - tensorflow-estimator
  - pip
  - pip:
    - keras-self-attention==0.42.0
    - pyyaml

